[sssd]
services = nss, pam, autofs, sudo
config_file_version = 2
domains = default

[domain/default]
id_provider = ldap
auth_provider = ldap
ldap_uri = ldap://finch
ldap_search_base = dc=fet,dc=local

# TLS/SSL Overrides
ldap_id_use_start_tls = False
ldap_auth_disable_tls_never_use_in_production = True
ldap_tls_reqcert = never

# Standard Schema Global Target Alignment
ldap_schema = rfc2307
ldap_user_search_base = dc=fet,dc=local
ldap_group_search_base = dc=fet,dc=local

# Explicit structural mappings for your exact LDIF data structures
ldap_group_object_class = posixGroup
ldap_group_name = cn
ldap_group_member = memberUid
ldap_user_uuid = uidNumber
ldap_group_uuid = gidNumber

# Keep your custom automount mapping schema alive below
autofs_provider = ldap
ldap_autofs_search_base = ou=autofs,dc=fet,dc=local
ldap_automount_map_object_class = organizationalUnit
ldap_automount_map_name = dn
ldap_automount_entry_object_class = automount
ldap_automount_entry_key = cn
ldap_automount_entry_value = automountInformation

# sudo rules
sudo_provider = ldap
ldap_sudo_search_base = ou=SUDOers,dc=fet,dc=local
